# Generated by Django 3.2.7 on 2021-09-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='corseSeason',
            new_name='courseSeason',
        ),
    ]
